# Generated by Django 5.1.4 on 2024-12-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Name')),
                ('color_code', models.CharField(max_length=50, verbose_name='Color Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('type', models.CharField(choices=[('utitlity', 'Utility'), ('food', 'Food'), ('education', 'Education'), ('transportation', 'Transportation'), ('medical', 'Medical'), ('internet & tv', 'Internet & TV'), ('entertainment', 'Entertainment'), ('salary', 'Salary'), ('other', 'Other')], max_length=50, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
            },
        ),
    ]
